name: CI
on:
  push:
  pull_request:
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve the code
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        working-directory: services/api
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt
      - name: Run test
        working-directory: services/api
        run: python -m pytest

  test-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve the code
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        working-directory: services/worker
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt
      - name: Run test
        working-directory: services/worker
        run: python -m pytest
  
  lint: 
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve the code
        uses: actions/checkout@v4
      - name: Install python
        uses: action/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install linting tools
        run: pip install black ruff
      - name: Check formatting with black
        run: black --check .
      - name: Lint with ruff
        run: ruff check .
