name: CI
on:
  push:
  pull_request:
jobs:
  test-api:
    uses: ./.github/workflows/test-service.yml
    with:
      service_path: services/api

  test-worker:
    uses: ./.github/workflows/test-service.yml
    with:
      service_path: services/worker  
  lint: 
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve the code
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install linting tools
        run: pip install black ruff
      - name: Check formatting with black
        run: black --check .
      - name: Lint with ruff
        run: ruff check .

  build-and-push:
    runs-on: ubuntu-latest
    needs: [test-api, test-worker, lint]
    steps:
      - name: Retrieve the code
        uses: actions/checkout@v4
      - name: Connection to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push API image
        uses: docker/build-push-action@v6
        with:
          context: ./services/api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/file-processing-api:latest

      - name: Build and push worker image
        uses: docker/build-push-action@v6
        with:
          context: ./services/worker
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/file-processing-worker:latest

